language: node_js
sudo: false
node_js:
- '10'
branches:
  only:
  - gh-pages
script:
  - npm install
  - for file in style*.json; do
      ./node_modules/.bin/gl-style-validate $file && diff <(./node_modules/.bin/gl-style-format $file) $file;
    done;
